syntax = "proto3";

package crypto.v1;
option go_package = "github.com/1337Bart/smol-crypto-api/api/proto/v1;cryptopb";

import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";
import "google/api/field_behavior.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: {
    title: "Crypto API";
    version: "1.0.0";
  }
};


message Crypto {
  string id = 1;
  string symbol = 2;
  string name = 3;
  double current_price = 4;
  double high_24h = 5;
  double low_24h = 6;
  double total_volume = 7;
  double market_cap = 8;
  int32 market_rank = 9;
  double price_change_24h = 10;
  double price_change_percentage_24h = 11;
  double circulating_supply = 12;
  double total_supply = 13;
  string timestamp = 14;
}

message ListCryptosRequest {
  PaginationRequest pagination = 1 [(google.api.field_behavior) = OPTIONAL];
  string symbol = 2 [(google.api.field_behavior) = OPTIONAL];
  google.protobuf.Timestamp start_time = 3 [(google.api.field_behavior) = OPTIONAL];
  google.protobuf.Timestamp end_time = 4 [(google.api.field_behavior) = OPTIONAL];
}

message PaginationRequest {
  int32 page = 1 [(google.api.field_behavior) = OPTIONAL];
  int32 limit = 2 [(google.api.field_behavior) = OPTIONAL];
}

message ListCryptosResponse {
  repeated Crypto cryptos = 1;
  int32 total_count = 2;
  int32 current_page = 3;
}

service CryptoService {
  rpc ListCryptos(ListCryptosRequest) returns (ListCryptosResponse) {
    option (google.api.http) = {
      get: "/api/v1/crypto"
      additional_bindings {
        get: "/v1/crypto"
      }
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "List all tracked cryptocurrencies"
      description: "Get a paginated list of all cryptocurrencies"
    };
  }
}